package org.github.unqui

import SpotifyService

private fun addSongs(spotifyService: SpotifyService) {
    spotifyService.addSong(SongDraft("Smells Like Teen Spirit", "Nirvana", "https://www.youtube.com/watch?v=hTWKbfoikeg", 279))
    spotifyService.addSong(SongDraft("Imagine", "John Lennon", "https://www.youtube.com/watch?v=bNnFFKv_NyI", 221))
    spotifyService.addSong(SongDraft("One", "U2", "https://www.youtube.com/watch?v=ftjEcrrf7r0", 274))
    spotifyService.addSong(SongDraft("Billie Jean", "Michael Jackson", "https://www.youtube.com/watch?v=Zi_XLOBDo_Y", 296))
    spotifyService.addSong(SongDraft("Bohemian Rhapsody", "Queen", "https://www.youtube.com/watch?v=fJ9rUzIMcZQ", 360))
    spotifyService.addSong(SongDraft("Hey Jude", "The Beatles", "https://www.youtube.com/watch?v=A_MjCqQoLLA", 490))
    spotifyService.addSong(SongDraft("Like A Rolling Stone", "Bob Dylan", "https://www.youtube.com/watch?v=IwOfCgkyEj0", 360))
    spotifyService.addSong(SongDraft("I Can't Get No Satisfaction", "Rolling Stones", "https://www.youtube.com/watch?v=nrIPxlFzDi0", 235))
    spotifyService.addSong(SongDraft("God Save The Queen", "Sex Pistols", "https://www.youtube.com/watch?v=yqrAPOZxgzU", 215))
    spotifyService.addSong(SongDraft("Sweet Child O'Mine", "Guns N' Roses", "https://www.youtube.com/watch?v=1w7OgIMMRc4", 303))
    spotifyService.addSong(SongDraft("London Calling", "The Clash", "https://www.youtube.com/watch?v=XN7iEFVLf5c", 200))
    spotifyService.addSong(SongDraft("Waterloo Sunset", "The Kinks", "https://www.youtube.com/watch?v=9Dbz5R8fO4Y", 199))
    spotifyService.addSong(SongDraft("Hotel California", "The Eagles", "https://www.youtube.com/watch?v=vydym4wh9Qo", 401))
    spotifyService.addSong(SongDraft("Your Song", "Elton John", "https://www.youtube.com/watch?v=GlPlfCy1urI", 229))
    spotifyService.addSong(SongDraft("Stairway To Heaven", "Led Zeppelin", "https://www.youtube.com/watch?v=QkF3oxziUI4", 483))
    spotifyService.addSong(SongDraft("The Twist", "Chubby Checker", "https://www.youtube.com/watch?v=pHGXwQeUk7M", 161))
    spotifyService.addSong(SongDraft("Live Forever", "Oasis", "https://www.youtube.com/watch?v=R2poqYvWsyU", 284))
    spotifyService.addSong(SongDraft("I Will Always Love You", "Whitney Houston", "https://www.youtube.com/watch?v=3JWTaaS7LdU", 274))
    spotifyService.addSong(SongDraft("Life On Mars?", "David Bowie", "https://www.youtube.com/watch?v=UipTt-qqZOE", 258))
    spotifyService.addSong(SongDraft("Heartbreak Hotel", "Elvis Presley", "https://www.youtube.com/watch?v=OP6qK589_Bo", 266))
    spotifyService.addSong(SongDraft("Over The Rainbow", "Judy Garland", "https://www.youtube.com/watch?v=BQqFq-ggiTc", 142))
    spotifyService.addSong(SongDraft("What's Goin' On", "Marvin Gaye", "https://www.youtube.com/watch?v=o5TmORitlKk", 240))
    spotifyService.addSong(SongDraft("Born To Run", "Bruce Springsteen", "https://www.youtube.com/watch?v=IxuThNgl3YA", 333))
    spotifyService.addSong(SongDraft("Be My Baby", "The Ronettes", "https://www.youtube.com/watch?v=jSPpbOGnFgk", 162))
    spotifyService.addSong(SongDraft("Creep", "Radiohead", "https://www.youtube.com/watch?v=XFkzRNyygfk", 236))
    spotifyService.addSong(SongDraft("Bridge Over Troubled Water", "Simon & Garfunkel", "https://www.youtube.com/watch?v=4G-YQA_bsOU", 294))
    spotifyService.addSong(SongDraft("Respect", "Aretha Franklin", "https://www.youtube.com/watch?v=6FOUqQt3Kg0", 150))
    spotifyService.addSong(SongDraft("Family Affair", "Sly And The Family Stone", "https://www.youtube.com/watch?v=xag5RKD0VHk", 187))
    spotifyService.addSong(SongDraft("Dancing Queen", "ABBA", "https://www.youtube.com/watch?v=xFrGuyw1V8s", 233))
    spotifyService.addSong(SongDraft("Good Vibrations", "The Beach Boys", "https://www.youtube.com/watch?v=Eab_beh07HU", 217))
    spotifyService.addSong(SongDraft("Purple Haze", "Jimi Hendrix", "https://www.youtube.com/watch?v=WGoDaYjdfSg", 172))
    spotifyService.addSong(SongDraft("Yesterday", "The Beatles", "https://www.youtube.com/watch?v=NrgmdOz227I", 125))
    spotifyService.addSong(SongDraft("Jonny B Good", "Chuck Berry", "https://www.youtube.com/watch?v=T38v3-SSGcM", 160))
    spotifyService.addSong(SongDraft("No Woman No Cry", "Bob Marley", "https://www.youtube.com/watch?v=pHlSE9j5FGY", 216))
    spotifyService.addSong(SongDraft("Hallelujah", "Jeff Buckley", "https://www.youtube.com/watch?v=y8AWFf7EAc4", 393))
    spotifyService.addSong(SongDraft("Every Breath You Take", "The Police", "https://www.youtube.com/watch?v=OMOGaugKpzs", 228))
    spotifyService.addSong(SongDraft("A Day In The Life", "The Beatles", "https://www.youtube.com/watch?v=usNsCeOV4GM", 312))
    spotifyService.addSong(SongDraft("Stand By Me", "Ben E King", "https://www.youtube.com/watch?v=einn_UJgGGM", 176))
    spotifyService.addSong(SongDraft("Papa's Got A Brand New Bag", "James Brown", "https://www.youtube.com/watch?v=QE5D2hJhacU", 259))
    spotifyService.addSong(SongDraft("Gimme Shelter", "The Rolling Stones", "https://www.youtube.com/watch?v=RbmS3tQJ7Os", 270))
    spotifyService.addSong(SongDraft("What'd I Say", "Ray Charles", "https://www.youtube.com/watch?v=EPLZL4s_jtI", 387))
    spotifyService.addSong(SongDraft("Sultans Of Swing", "Dire Straits", "https://www.youtube.com/watch?v=0fAQhSRLQnM", 346))
    spotifyService.addSong(SongDraft("God Only Knows", "The Beach Boys", "https://www.youtube.com/watch?v=CWPo5SC3zik", 173))
    spotifyService.addSong(SongDraft("You've Lost That Lovin' Feeling", "The Righteous Brothers", "https://www.youtube.com/watch?v=uOnYY9Mw2Fg", 226))
    spotifyService.addSong(SongDraft("My Generation", "The Who", "https://www.youtube.com/watch?v=qN5zw04WxCc", 207))
    spotifyService.addSong(SongDraft("Dancing In The Street", "Martha Reeves and the Vandellas", "https://www.youtube.com/watch?v=9KhbM2mqhCQ", 157))
    spotifyService.addSong(SongDraft("When Doves Cry", "Prince", "https://www.youtube.com/watch?v=UG3VcCAlUgE", 224))
    spotifyService.addSong(SongDraft("A Change Is Gonna Come", "Sam Cooke", "https://www.youtube.com/watch?v=wEBlaMOmKV4", 190))
    spotifyService.addSong(SongDraft("River Deep Mountain High", "Ike and Tina Turner", "https://www.youtube.com/watch?v=jhkIh4x4mmM", 271))
    spotifyService.addSong(SongDraft("Best Of My Love", "The Emotions", "https://www.youtube.com/watch?v=WPefERS7EZs", 217))
    spotifyService.addSong(SongDraft("Dynamite", "BTS", "https://www.youtube.com/watch?v=gdZLi9oWNZg", 224))
    spotifyService.addSong(SongDraft("Living The Dream", "Sturgill Simpson", "https://www.youtube.com/watch?v=IhKSTg9f1DI", 150))
    spotifyService.addSong(SongDraft("pov", "Ariana Grande", "https://www.youtube.com/watch?v=nQJEp-k-ogs", 203))
    spotifyService.addSong(SongDraft("Look Over Your Shoulder", "Busta Rhymes (feat. Kendrick Lamar)", "https://www.youtube.com/watch?v=Yl_-3oSlWaU", 284))
    spotifyService.addSong(SongDraft("Color my life", "Chicano Batman", "https://www.youtube.com/watch?v=J7ZHahLLpPQ", 208))
    spotifyService.addSong(SongDraft("Dangerous Love (DJ Tunez & D3an Remix)", "Tiwa Savage", "https://www.youtube.com/watch?v=uuZuOu13Q7Y", 149))
    spotifyService.addSong(SongDraft("My Truck (Remix)", "Breland (feat. Sam Hunt)", "https://www.youtube.com/watch?v=MgPUyq4VqGI", 167))
    spotifyService.addSong(SongDraft("Sweeter", "Leon Bridges (feat. Terrace Martin)", "https://www.youtube.com/watch?v=35AWgksymtA", 170))
    spotifyService.addSong(SongDraft("Cool For A Second", "Yumi Zouma", "https://www.youtube.com/watch?v=x7Kt_YAQQgM", 190))
    spotifyService.addSong(SongDraft("Simmer", "Hayley Williams", "https://www.youtube.com/watch?v=8lSj5k2K7w0", 287))
    spotifyService.addSong(SongDraft("If You're Too Shy (Let Me Know)", "The 1975", "https://www.youtube.com/watch?v=wYYQpTbBSBM", 335))
    spotifyService.addSong(SongDraft("Billy", "Swamp Dogg", "https://www.youtube.com/watch?v=GPJCsTOuT_c", 165))
    spotifyService.addSong(SongDraft("Just Constellations No. 1, The Opening Constellation (Summer)", "Roomful Of Teeth", "https://www.youtube.com/watch?v=Al7CRbchTTM", 483))
    spotifyService.addSong(SongDraft("Still Your Best", "GIVĒON", "https://www.youtube.com/watch?v=c69BWaYnKHI", 179))
    spotifyService.addSong(SongDraft("Said Sum", "Moneybagg Yo", "https://www.youtube.com/watch?v=T8pi91qWnRw", 178))
    spotifyService.addSong(SongDraft("Mandinga Times", "Rita Indiana (feat. Kiko El Crazy)", "https://www.youtube.com/watch?v=6gZLlBEHA-c", 211))
    spotifyService.addSong(SongDraft("Cry", "Ashnikko (feat. Grimes)", "https://www.youtube.com/watch?v=pssWSj42t8M", 126))
    spotifyService.addSong(SongDraft("Tin King", "Ultraísta", "https://www.youtube.com/watch?v=wN8_e8Bma3I", 291))
    spotifyService.addSong(SongDraft("Hunger For A Way Out", "Sweeping Promises", "https://www.youtube.com/watch?v=paC0vq5WdoE", 141))
    spotifyService.addSong(SongDraft("Die Midwestern", "Arlo McKinley", "https://www.youtube.com/watch?v=JVLdTjoWUME", 254))
    spotifyService.addSong(SongDraft("Hit Different", "SZA (feat. Ty Dolla ign)", "https://www.youtube.com/watch?v=qJlMkMtK7-8", 313))
    spotifyService.addSong(SongDraft("Right Back Round Again", "Joshua Redman, Brad Mehldau, Christian McBride & Brian Blade", "https://www.youtube.com/watch?v=cwn6dgDFJlE", 636))
    spotifyService.addSong(SongDraft("The Arts and the Hours", "Víkingur Ólafsson", "https://www.youtube.com/watch?v=qTwqBVt2Clw", 286))
    spotifyService.addSong(SongDraft("I Know The End", "Phoebe Bridgers", "https://www.youtube.com/watch?v=WJ9-xN6dCW4", 347))
    spotifyService.addSong(SongDraft("Starting Over", "Chris Stapleton", "https://www.youtube.com/watch?v=A3svABDnmio", 258))
    spotifyService.addSong(SongDraft("On The Floor", "Perfume Genius", "https://www.youtube.com/watch?v=ln4S83JeY2Y", 361))
    spotifyService.addSong(SongDraft("Repeat", "J Hus (feat. Koffee)", "https://www.youtube.com/watch?v=PSFN8bAIkmQ", 155))
    spotifyService.addSong(SongDraft("Small Town Hypocrite", "Caylee Hammack", "https://www.youtube.com/watch?v=9L9obo3cuas", 240))
    spotifyService.addSong(SongDraft("Lost One", "Jazmine Sullivan", "https://www.youtube.com/watch?v=1NMz1jsoNoU", 182))
    spotifyService.addSong(SongDraft("Hard to Forget", "Sam Hunt", "https://www.youtube.com/watch?v=Wxhv_HsEIl4", 212))
    spotifyService.addSong(SongDraft("South Gotta Change", "Adia Victoria", "https://www.youtube.com/watch?v=XEm0qOxhGxo", 237))
    spotifyService.addSong(SongDraft("Antifa Dance", "Ana Tijoux", "https://www.youtube.com/watch?v=tksolV5Gkso", 189))
    spotifyService.addSong(SongDraft("Dragonball Durag", "Thundercat", "https://www.youtube.com/watch?v=ormQQG2UhtQ", 182))
    spotifyService.addSong(SongDraft("Murder Most Foul", "Bob Dylan", "https://www.youtube.com/watch?v=3NbQkyvbw18", 1017))
    spotifyService.addSong(SongDraft("anything", "Adrianne Lenker", "https://www.youtube.com/watch?v=Bs4MffKz9rk", 201))
    spotifyService.addSong(SongDraft("Safaera", "Bad Bunny (feat. Jowell & Randy and Ñengo Flow)", "https://www.youtube.com/watch?v=jCQ_6XbATPc", 296))
    spotifyService.addSong(SongDraft("Black Like Me", "Mickey Guyton", "https://www.youtube.com/watch?v=ZXKsmR44IP8", 213))
    spotifyService.addSong(SongDraft("Savage Remix", "Megan Thee Stallion (feat. Beyoncé)", "https://www.youtube.com/watch?v=lEIqjoO0-Bs", 242))
    spotifyService.addSong(SongDraft("People, I've been sad", "Christine and the Queens", "https://www.youtube.com/watch?v=mYHAnuBKV-o", 260))
    spotifyService.addSong(SongDraft("WAP", "Cardi B (feat. Megan Thee Stallion)", "https://www.youtube.com/watch?v=hsm4poTWjMs", 253))
}

private fun addUsers(spotifyService: SpotifyService) {
    spotifyService.register(UserDraft("jania@gmail.com", "https://robohash.org/eumutvoluptatem.jpg?size=50x50&set=set1", "jania", "jania"))
    spotifyService.register(UserDraft("tiebold@gmail.com", "https://robohash.org/eumquoasperiores.png?size=50x50&set=set1", "tiebold", "tiebold"))
    spotifyService.register(UserDraft("corella@gmail.com", "https://robohash.org/essedebitisneque.jpg?size=50x50&set=set1", "corella", "corella"))
    spotifyService.register(UserDraft("curry@gmail.com", "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1", "curry", "curry"))
    spotifyService.register(UserDraft("berny@gmail.com", "https://robohash.org/sitquisat.png?size=50x50&set=set1", "berny", "berny"))
    spotifyService.register(UserDraft("chip@gmail.com", "https://robohash.org/aconsequatureos.png?size=50x50&set=set1", "chip", "chip"))
    spotifyService.register(UserDraft("sandie@gmail.com", "https://robohash.org/praesentiumvoluptatibuscommodi.jpg?size=50x50&set=set1", "sandie", "sandie"))
    spotifyService.register(UserDraft("nye@gmail.com", "https://robohash.org/adipisciinillo.png?size=50x50&set=set1", "nye", "nye"))
    spotifyService.register(UserDraft("tallia@gmail.com", "https://robohash.org/nonharumautem.png?size=50x50&set=set1", "tallia", "tallia"))
    spotifyService.register(UserDraft("ashlen@gmail.com", "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1", "ashlen", "ashlen"))
    spotifyService.register(UserDraft("woodman@gmail.com", "https://robohash.org/temporedolorumunde.bmp?size=50x50&set=set1", "woodman", "woodman"))
    spotifyService.register(UserDraft("kacie@gmail.com", "https://robohash.org/veritatisiurevoluptatem.jpg?size=50x50&set=set1", "kacie", "kacie"))
    spotifyService.register(UserDraft("des@gmail.com", "https://robohash.org/omnispossimusprovident.png?size=50x50&set=set1", "des", "des"))
    spotifyService.register(UserDraft("adrienne@gmail.com", "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1", "adrienne", "adrienne"))
    spotifyService.register(UserDraft("rebecka@gmail.com", "https://robohash.org/voluptatedoloremut.bmp?size=50x50&set=set1", "rebecka", "rebecka"))
    spotifyService.register(UserDraft("emilia@gmail.com", "https://robohash.org/aperiaminmolestiae.bmp?size=50x50&set=set1", "emilia", "emilia"))
    spotifyService.register(UserDraft("mallorie@gmail.com", "https://robohash.org/quiquasinihil.jpg?size=50x50&set=set1", "mallorie", "mallorie"))
    spotifyService.register(UserDraft("octavia@gmail.com", "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1", "octavia", "octavia"))
    spotifyService.register(UserDraft("palmer@gmail.com", "https://robohash.org/nemosequilaudantium.jpg?size=50x50&set=set1", "palmer", "palmer"))
    spotifyService.register(UserDraft("nicko@gmail.com", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "nicko", "nicko"))
    spotifyService.register(UserDraft("juan@gmail.com", "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1", "juan", "juan"))
    spotifyService.register(UserDraft("rodrigo@gmail.com", "https://robohash.org/voluptatedoloremut.bmp?size=50x50&set=set1", "rodrigo", "rodrigo"))
    spotifyService.register(UserDraft("jesus@gmail.com", "https://robohash.org/aperiaminmolestiae.bmp?size=50x50&set=set1", "jesus", "jesus"))
    spotifyService.register(UserDraft("pepe@gmail.com", "https://robohash.org/quiquasinihil.jpg?size=50x50&set=set1", "pepe", "pepe"))
    spotifyService.register(UserDraft("martin@gmail.com", "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1", "martin", "martin"))
    spotifyService.register(UserDraft("ines@gmail.com", "https://robohash.org/nemosequilaudantium.jpg?size=50x50&set=set1", "ines", "ines"))
    spotifyService.register(UserDraft("flor@gmail.com", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "flor", "flor"))
    spotifyService.register(UserDraft("a@gmail.com", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "a", "a"))
    spotifyService.register(UserDraft("b@gmail.com", "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1", "b", "b"))
    spotifyService.register(UserDraft("c@gmail.com", "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1", "c", "c"))
}

private fun getSongsOf(allSongs: List<Song>, list: List<Int>): MutableList<Song> {
    return list.map { allSongs[it] }.toMutableList()
}

private fun addPlaylist(spotifyService: SpotifyService) {
    addNewPlaylist(spotifyService, "user_0", "logograms", "My co-worker Tyron has one of these. He says it looks stout.", listOf(77,34,13,51,63,89,20,71,11,74,24,35,1,74), "https://picsum.photos/id/117/1544/1024")
    addNewPlaylist(spotifyService, "user_1", "dishonorer", "one of my hobbies is gaming. and when i'm gaming this works great.", listOf(14,36,87,80,77,4,88,70,42,87), "https://picsum.photos/id/118/1500/1000")
    addNewPlaylist(spotifyService, "user_2", "sim", "My co-worker Luka has one of these. He says it looks purple.", listOf(83,7,3,81,33,89,60,10,48,69,48,8,52,44,15), "https://picsum.photos/id/119/3264/2176")
    addNewPlaylist(spotifyService, "user_3", "dilapidator", "this Songs is gracious.", listOf(11,78,18,43,24,29,22,63,66,86,50,69,43,69,49), "https://picsum.photos/id/12/2500/1667")
    addNewPlaylist(spotifyService, "user_4", "extractive", "It only works when I'm Niue.", listOf(43,50,57), "https://picsum.photos/id/120/4928/3264")
    addNewPlaylist(spotifyService, "user_5", "archduchy", "My hummingbird loves to play with it.", listOf(84,16,65,79,81,66,87,24,89,64,88,72,55,59,82), "https://picsum.photos/id/121/1600/1067")
    addNewPlaylist(spotifyService, "user_6", "paramedic", "I tried to shatter it but got potato all over it.", listOf(26,77,24,1,47,77,32,40,55,60,41), "https://picsum.photos/id/122/4147/2756")
    addNewPlaylist(spotifyService, "user_7", "tremulousness", "heard about this on bouyon radio, decided to give it a try.", listOf(22,53,84,12,21,60,88,80,85,87,23,0,37,37), "https://picsum.photos/id/123/4928/3264")
    addNewPlaylist(spotifyService, "user_8", "match", "It only works when I'm Kuwait.", listOf(85,27,83,87,15,8,84,48), "https://picsum.photos/id/124/3504/2336")
    addNewPlaylist(spotifyService, "user_9", "algology", "I saw one of these in Sao Tome and Principe and I bought one.", listOf(71,75,74,12,62,20,30,21), "https://picsum.photos/id/125/1500/1000")
    addNewPlaylist(spotifyService, "user_10", "cuneiform", "I tried to maul it but got onion all over it.", listOf(47,2,10,7,49,48,48,77,34), "https://picsum.photos/id/126/4272/2511")
    addNewPlaylist(spotifyService, "user_11", "sinecurists", "It only works when I'm Juan de Nova Island.", listOf(70,79,52,0,16,82,22), "https://picsum.photos/id/127/4032/2272")
    addNewPlaylist(spotifyService, "user_12", "hetaera", "talk about optimism!!!", listOf(76,76,65,37,67,0,71,53,53,35), "https://picsum.photos/id/128/3823/2549")
    addNewPlaylist(spotifyService, "user_13", "inflorescences", "one of my hobbies is skateboarding. and when i'm skateboarding this works great.", listOf(80,6,21), "https://picsum.photos/id/129/4910/3252")
    addNewPlaylist(spotifyService, "user_14", "imprecision", "This Songs works excessively well. It speedily improves my baseball by a lot.", listOf(37,77,48,7,59,11,84,25,1,15,78,37), "https://picsum.photos/id/13/2500/1667")
    addNewPlaylist(spotifyService, "user_15", "rabbinates", "I tried to nab it but got biscuit all over it.", listOf(75,82,7,45,89,21,1,1,30), "https://picsum.photos/id/130/3807/2538")
    addNewPlaylist(spotifyService, "user_16", "pole", "this Songs is revolting.", listOf(49,33,59,51,30,39,14,74,10,3), "https://picsum.photos/id/131/4698/3166")
    addNewPlaylist(spotifyService, "user_17", "fornixes", "this Songs is hyper.", listOf(89,84,31), "https://picsum.photos/id/132/1600/1066")
    addNewPlaylist(spotifyService, "user_18", "afflictions", "this Songs is smooth.", listOf(36,64,35,48,83,46,12), "https://picsum.photos/id/133/2742/1828")
    addNewPlaylist(spotifyService, "user_19", "sob", "The box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!", listOf(15,48,87,34,45,48,34,39,36,84,0,77), "https://picsum.photos/id/134/4928/3264")
    addNewPlaylist(spotifyService, "user_20", "derogations", "talk about bliss!!", listOf(81,52,39,48,31,89,18,20,51,54,22), "https://picsum.photos/id/135/2560/1920")
    addNewPlaylist(spotifyService, "user_21", "dustups", "The box this comes in is 4 mile by 5 inch and weights 19 megaton!", listOf(76,74,80), "https://picsum.photos/id/136/4032/2272")
    addNewPlaylist(spotifyService, "user_22", "hunchbacks", "This Songs works certainly well. It excitedly improves my football by a lot.", listOf(42,40,22,28,30,26), "https://picsum.photos/id/137/4752/3168")
    addNewPlaylist(spotifyService, "user_23", "mandiocas", "SoCal cockroaches are unwelcome, crafty, and tenacious. This Songs keeps them away.", listOf(2,42,27,27,27,43,37,50,58,5,58,28), "https://picsum.photos/id/139/3465/3008")
    addNewPlaylist(spotifyService, "user_24", "experimentalist", "The box this comes in is 5 kilometer by 6 meter and weights 20 ounce!", listOf(9,17,80,23,52,54,48,62), "https://picsum.photos/id/14/2500/1667")
    addNewPlaylist(spotifyService, "user_25", "galactagogue", "My neighbor Aldona has one of these. She works as a butler and she says it looks humongous.", listOf(25,70,57,32,9,76,48,10,29,46,37,21,13,11), "https://picsum.photos/id/140/2448/2448")
    addNewPlaylist(spotifyService, "user_26", "lectureships", "this Songs is honest.", listOf(22,18,17), "https://picsum.photos/id/141/2048/1365")
    addNewPlaylist(spotifyService, "user_27", "incumbent", "The box this comes in is 3 kilometer by 5 inch and weights 13 ton.", listOf(23,3,43), "https://picsum.photos/id/142/4272/2848")
    addNewPlaylist(spotifyService, "user_28", "overgrowth", "heard about this on original pilipino music radio, decided to give it a try.", listOf(61,79,40,68,16), "https://picsum.photos/id/143/3600/2385")
    addNewPlaylist(spotifyService, "user_0", "variable", "I tried to nab it but got salad all over it.", listOf(50,5,22,43,72,87,27), "https://picsum.photos/id/144/4912/2760")
    addNewPlaylist(spotifyService, "user_1", "intrepidity", "My bass loves to play with it.", listOf(77,14,78,28,13,21,19,47,2,48,2,87,46,43,47), "https://picsum.photos/id/145/4288/2848")
    addNewPlaylist(spotifyService, "user_2", "aleurone", "My co-worker Bryton has one of these. He says it looks ragged.", listOf(46,36,22,11,25), "https://picsum.photos/id/146/5184/3456")
    addNewPlaylist(spotifyService, "user_3", "medicks", "This Songs works certainly well. It energetically improves my golf by a lot.", listOf(49,59,84,85,49,23,6,8,54,18), "https://picsum.photos/id/147/2448/2448")
    addNewPlaylist(spotifyService, "user_4", "divisor", "The box this comes in is 4 kilometer by 5 mile and weights 17 gram.", listOf(62,18,56,55,30,15,21,26), "https://picsum.photos/id/149/3454/2288")
    addNewPlaylist(spotifyService, "user_5", "typist", "one of my hobbies is piano. and when i'm playing piano this works great.", listOf(72,38,41,52,46,85,2,27,9,71,64,18), "https://picsum.photos/id/15/2500/1667")
    addNewPlaylist(spotifyService, "user_6", "clavicorn", "talk about hatred.", listOf(33,69,37,44,66,0,33,83,83,24,38,1), "https://picsum.photos/id/151/4288/3216")
    addNewPlaylist(spotifyService, "user_7", "carrot", "My co-worker Nile has one of these. He says it looks crooked.", listOf(81,61,75,35,53,21,36,78,72), "https://picsum.photos/id/152/3888/2592")
    addNewPlaylist(spotifyService, "user_8", "exsiccators", "one of my hobbies is spearfishing. and when i'm spearfishing this works great.", listOf(15,48,86,76,85), "https://picsum.photos/id/153/4763/3155")
    addNewPlaylist(spotifyService, "user_9", "salience", "The box this comes in is 5 kilometer by 5 inch and weights 13 kilogram!!!", listOf(5,45,37,25,5,48,56,89,9,16,29), "https://picsum.photos/id/154/3264/2176")
    addNewPlaylist(spotifyService, "user_10", "intransigeance", "I saw one of these in French Southern and Antarctic Lands and I bought one.", listOf(89,40,46,18,19,64), "https://picsum.photos/id/155/3264/2176")
    addNewPlaylist(spotifyService, "user_11", "imports", "one of my hobbies is guitar. and when i'm playing guitar this works great.", listOf(14,29,11,65,13,81,64,70,68,28), "https://picsum.photos/id/156/2177/3264")
    addNewPlaylist(spotifyService, "user_12", "fryings", "I saw one of these in Macau and I bought one.", listOf(51,39,79,28,3,74,23,77,17,67,83,53), "https://picsum.photos/id/157/6211/4862")
    addNewPlaylist(spotifyService, "user_13", "maneater", "My terrier loves to play with it.", listOf(2,35,34,33,14,48,14,56,1), "https://picsum.photos/id/158/4836/3224")
    addNewPlaylist(spotifyService, "user_14", "camelot", "The box this comes in is 3 centimeter by 5 kilometer and weights 13 ounce!!", listOf(66,10,42,81), "https://picsum.photos/id/159/5184/2551")
    addNewPlaylist(spotifyService, "user_15", "pundits", "The box this comes in is 4 mile by 5 inch and weights 19 megaton!", listOf(48,72,62,88,56,32,13,58,19,71,7,81), "https://picsum.photos/id/16/2500/1667")
    addNewPlaylist(spotifyService, "user_16", "dapperness", "This Songs works really well. It wildly improves my baseball by a lot.", listOf(58,74,80), "https://picsum.photos/id/160/3200/2119")
    addNewPlaylist(spotifyService, "user_17", "monisms", "I tried to strangle it but got hazelnut all over it.", listOf(59,52,62,36,35), "https://picsum.photos/id/161/4240/2832")
    addNewPlaylist(spotifyService, "user_18", "barramundi", "heard about this on chicha radio, decided to give it a try.", listOf(69,65,69,12), "https://picsum.photos/id/162/1500/998")
    addNewPlaylist(spotifyService, "user_19", "tymbal", "heard about this on bouyon radio, decided to give it a try.", listOf(79,16,87,73,47,75,76,8,62,70,68,34,50,73,4), "https://picsum.photos/id/163/2000/1333")
    addNewPlaylist(spotifyService, "user_20", "obscurities", "My co-worker Matthew has one of these. He says it looks gigantic.", listOf(53,56,33,23,88,32,29,42), "https://picsum.photos/id/164/1200/800")
    addNewPlaylist(spotifyService, "user_21", "catchings", "talk about anticipation!", listOf(8,65,65,52,35,37,77,19,8,22), "https://picsum.photos/id/165/2000/1333")
    addNewPlaylist(spotifyService, "user_22", "torbanite", "The box this comes in is 5 yard by 6 centimeter and weights 12 kilogram.", listOf(37,3,38,48,69,41,21,74,70,88,69,84,21), "https://picsum.photos/id/166/1280/720")
    addNewPlaylist(spotifyService, "user_23", "sunks", "I tried to kidnap it but got apricot all over it.", listOf(33,76,44,52,55,49,70,66,28,64,42,5,18,58), "https://picsum.photos/id/167/2896/1944")
    addNewPlaylist(spotifyService, "user_24", "parkland", "heard about this on dance-rock radio, decided to give it a try.", listOf(11,39,73,81,44), "https://picsum.photos/id/168/1920/1280")
    addNewPlaylist(spotifyService, "user_25", "ichthyolites", "one of my hobbies is guitar. and when i'm playing guitar this works great.", listOf(6,41,3,56,72,39), "https://picsum.photos/id/169/2500/1662")
    addNewPlaylist(spotifyService, "user_26", "solferinos", "This Songs works excessively well. It mortally improves my golf by a lot.", listOf(87,24,82,56,22,87,45,24,36,1,79), "https://picsum.photos/id/17/2500/1667")
    addNewPlaylist(spotifyService, "user_27", "solving", "I tried to attack it but got meatball all over it.", listOf(12,7,57,1,8,39,29,44,34,7,50,79,2,47), "https://picsum.photos/id/170/2500/1667")
    addNewPlaylist(spotifyService, "user_28", "pastoralists", "My co-worker Bryton has one of these. He says it looks ragged.", listOf(39,30,42,0,53,1,24,53,5,17), "https://picsum.photos/id/171/2048/1536")
    addNewPlaylist(spotifyService, "user_0", "spendthrifts", "It only works when I'm Nepal.", listOf(77,29,11,69,3,9,76,70,84,85,53,30), "https://picsum.photos/id/172/2000/1325")
    addNewPlaylist(spotifyService, "user_2", "diffusedness", "heard about this on original pilipino music radio, decided to give it a try.", listOf(6,79,26,39,4,31,74,37,1), "https://picsum.photos/id/173/1200/737")
    addNewPlaylist(spotifyService, "user_4", "swimmerets", "i use it until further notice when i'm in my nightclub.", listOf(35,21,36,40,86,42), "https://picsum.photos/id/174/1600/589")
    addNewPlaylist(spotifyService, "user_6", "meths", "My neighbor Krista has one of these. She works as a salesman and she says it looks soapy.", listOf(70,17,88,81,39,32,27,60,71,63,54), "https://picsum.photos/id/175/2896/1944")
    addNewPlaylist(spotifyService, "user_8", "hulling", "talk about pleasure!", listOf(79,72,49,16,4), "https://picsum.photos/id/176/2500/1662")
    addNewPlaylist(spotifyService, "user_10", "glyphographers", "I saw one of these in Canada and I bought one.", listOf(65,15,88,63,4,41,80,43), "https://picsum.photos/id/177/2515/1830")
    addNewPlaylist(spotifyService, "user_12", "commodore", "i use it profusely when i'm in my garage.", listOf(3,12,7,1,51,72,7,24,43,19,22,25,88,3,6), "https://picsum.photos/id/178/2592/1936")
    addNewPlaylist(spotifyService, "user_14", "verbalisms", "The box this comes in is 3 inch by 6 centimeter and weights 15 ounce!", listOf(10,83,58,82,54,32,34), "https://picsum.photos/id/179/2048/1365")
    addNewPlaylist(spotifyService, "user_16", "vakeel", "i use it this time when i'm in my port-a-potty.", listOf(43,17,0,62,53,30,19,45,41,83,21,69,87), "https://picsum.photos/id/18/2500/1667")
    addNewPlaylist(spotifyService, "user_18", "ponchos", "It only works when I'm Niger.", listOf(77,53,48,78,9,61,83,50,26,31,70,43,71,80,78), "https://picsum.photos/id/180/2400/1600")
    addNewPlaylist(spotifyService, "user_20", "seringa", "this Songs is perplexed.", listOf(53,3,73,44,29,60,3,0,10,81,65,64), "https://picsum.photos/id/181/1920/1189")
    addNewPlaylist(spotifyService, "user_22", "downcomer", "This Songs works too well. It buoyantly improves my football by a lot.", listOf(15,70,58,89,20,15,19,88,0,59,38,73), "https://picsum.photos/id/182/2896/1944")
    addNewPlaylist(spotifyService, "user_24", "flaunt", "The box this comes in is 3 light-year by 5 meter and weights 10 ounce!", listOf(61,87,63,38,18,66,62,83,53,54,75,37,0,0), "https://picsum.photos/id/183/2316/1544")
    addNewPlaylist(spotifyService, "user_26", "objectivity", "This Songs works very well. It romantically improves my football by a lot.", listOf(24,39,61,44,43,11,6,25,2,81), "https://picsum.photos/id/184/4288/2848")
    addNewPlaylist(spotifyService, "user_28", "cambrels", "It only works when I'm Azerbaijan.", listOf(23,60,69,52,56,57), "https://picsum.photos/id/185/3995/2662")
}

private fun addNewPlaylist(spotifyService: SpotifyService, user: String, name: String, description: String, songs: List<Int>, image: String) {
    spotifyService.addPlaylist(user, PlayListDraft(name, description, image, getSongsOf(spotifyService.getAllSongs(), songs)))
}

private fun addLikes(spotifyService: SpotifyService) {
    likes(spotifyService, "user_0", listOf("playlist_5","playlist_16","playlist_24","playlist_57","playlist_40","playlist_28"))
    likes(spotifyService, "user_1", listOf("playlist_53","playlist_8","playlist_63"))
    likes(spotifyService, "user_2", listOf("playlist_57","playlist_34","playlist_66","playlist_56","playlist_15","playlist_18","playlist_38","playlist_29","playlist_58","playlist_54","playlist_48"))
    likes(spotifyService, "user_3", listOf("playlist_49","playlist_45","playlist_42","playlist_70","playlist_37","playlist_2","playlist_53","playlist_60","playlist_46","playlist_34","playlist_23","playlist_12","playlist_31"))
    likes(spotifyService, "user_4", listOf("playlist_47","playlist_53","playlist_35","playlist_67","playlist_0","playlist_28","playlist_34","playlist_52","playlist_61"))
    likes(spotifyService, "user_5", listOf("playlist_20","playlist_11","playlist_59","playlist_9"))
    likes(spotifyService, "user_6", listOf("playlist_71","playlist_71","playlist_46","playlist_60","playlist_36","playlist_23","playlist_60","playlist_59","playlist_22","playlist_58","playlist_66","playlist_69","playlist_55","playlist_15","playlist_57"))
    likes(spotifyService, "user_7", listOf("playlist_48","playlist_52","playlist_16","playlist_9","playlist_1","playlist_17","playlist_65"))
    likes(spotifyService, "user_8", listOf("playlist_27","playlist_65","playlist_16","playlist_50"))
    likes(spotifyService, "user_9", listOf("playlist_40","playlist_15","playlist_64","playlist_43","playlist_19"))
    likes(spotifyService, "user_10", listOf("playlist_24","playlist_39","playlist_35","playlist_18","playlist_50","playlist_38","playlist_11","playlist_45","playlist_52"))
    likes(spotifyService, "user_11", listOf("playlist_48","playlist_67","playlist_21"))
    likes(spotifyService, "user_12", listOf("playlist_51","playlist_46","playlist_35","playlist_56","playlist_52"))
    likes(spotifyService, "user_13", listOf("playlist_45","playlist_44","playlist_20","playlist_14","playlist_54","playlist_30","playlist_18"))
    likes(spotifyService, "user_14", listOf("playlist_44","playlist_46","playlist_2","playlist_3","playlist_32","playlist_31","playlist_72","playlist_17","playlist_63","playlist_60","playlist_11","playlist_5","playlist_36","playlist_62","playlist_37"))
    likes(spotifyService, "user_15", listOf("playlist_13","playlist_53","playlist_51","playlist_24","playlist_65","playlist_19","playlist_57","playlist_65","playlist_4","playlist_25","playlist_16","playlist_18","playlist_65","playlist_70"))
    likes(spotifyService, "user_16", listOf("playlist_18","playlist_1","playlist_9","playlist_39","playlist_39","playlist_33"))
    likes(spotifyService, "user_17", listOf("playlist_63","playlist_2","playlist_30","playlist_17","playlist_27","playlist_15","playlist_24","playlist_4","playlist_20","playlist_35","playlist_1","playlist_67","playlist_64","playlist_19"))
    likes(spotifyService, "user_18", listOf("playlist_46","playlist_52","playlist_35","playlist_19","playlist_46","playlist_59","playlist_31","playlist_1","playlist_37","playlist_49","playlist_68"))
    likes(spotifyService, "user_19", listOf("playlist_46","playlist_9","playlist_24","playlist_54","playlist_70","playlist_4","playlist_46","playlist_63","playlist_23","playlist_24"))
    likes(spotifyService, "user_20", listOf("playlist_46","playlist_46","playlist_17","playlist_45","playlist_66","playlist_63","playlist_55"))
    likes(spotifyService, "user_21", listOf("playlist_24","playlist_21","playlist_71","playlist_42","playlist_29"))
    likes(spotifyService, "user_22", listOf("playlist_45","playlist_40","playlist_53","playlist_52","playlist_14","playlist_63","playlist_36","playlist_64"))
    likes(spotifyService, "user_23", listOf("playlist_32","playlist_10","playlist_22","playlist_20","playlist_45","playlist_63","playlist_67","playlist_5","playlist_41","playlist_0","playlist_16","playlist_26","playlist_46","playlist_30","playlist_47"))
    likes(spotifyService, "user_24", listOf("playlist_9","playlist_29","playlist_8","playlist_28","playlist_29"))
    likes(spotifyService, "user_25", listOf("playlist_48","playlist_49","playlist_56","playlist_15","playlist_38","playlist_37"))
    likes(spotifyService, "user_26", listOf("playlist_53","playlist_36","playlist_8","playlist_29","playlist_39"))
    likes(spotifyService, "user_27", listOf("playlist_15","playlist_53","playlist_50","playlist_47","playlist_32","playlist_13","playlist_60","playlist_11","playlist_39","playlist_40","playlist_59","playlist_31","playlist_3"))
    likes(spotifyService, "user_28", listOf("playlist_10","playlist_33","playlist_30","playlist_40","playlist_49","playlist_30","playlist_53"))
}

private fun likes(spotifyService: SpotifyService, userId: String, listOfPlaylist: List<String>) {
    listOfPlaylist.forEach {
        spotifyService.addOrRemoveLike(userId, it)
    }
}

fun getSpotifyService(): SpotifyService {
    val spotifyService = SpotifyService(mutableListOf(), mutableListOf(), mutableListOf())
    addSongs(spotifyService)
    addUsers(spotifyService)
    addPlaylist(spotifyService)
    addLikes(spotifyService)
    return spotifyService
}